### ISSUE TITLE
Add a route to log out the current user

### ISSUE THREAD

**Issue by WhitingJarod** [astonhaycock/RecipeVision#6]
Suggested route: `POST /api/logout`
This should log out the current user. Yay.

**Comment by iamworrell** [comment]
can you assign this task to me?

**Comment by WhitingJarod** [comment]
It's assigned. You'll need to either work in the express_routes branch, or wait for the pull request to go through.

**Comment by WhitingJarod** [comment]
> can you assign this task to me?

My bad, I missed your name and assumed you were Aston. I apologize. We'd love the the help, but this is a university project that Aston and I need to work on together.

**Comment by iamworrell** [comment]
ok no problem
